time:
  total_time: 100.0
  step: 0.1

domain:
  min: -60.0
  max: 60.0
  step: 20.0

use_2d: True

objects:
  cell_radius: 8.0
  cell_interaction_factor: 1.25
  neurite_radius: 0.5
  neurite_interaction_factor: 1.25
  neurite_spring_constant: 10.0
  neurite_default_length: 10.0

interactions:
  type: "potentials"
  sphere_sphere_adhesion: 4.0
  sphere_sphere_repulsion: 50.0
  sphere_sphere_smoothness: 1
  sphere_cylinder_adhesion: 5.0
  sphere_cylinder_repulsion: 10.0
  sphere_cylinder_smoothness: 1
  cylinder_cylinder_adhesion: 10.0
  cylinder_cylinder_repulsion: 10.0
  cylinder_cyliner_smoothness: 1