# Simulation time [minutes]
time:
  total_time: 1440.0
  step: 0.1

# Domain options
domain:
  # Domain size [microns]
  boundaries:
    min: -300.0
    max: 300.0
    step: 20.0

  # 2D status [True for 2D / False for 3D]
  use_2d: True

  # Drag coefficent [Pa*s]
  drag_coefficient: 10.0

# Neuron objects
neurons:
  # Physical objects properties
  objects:
    cell_radius: 8.0
    cell_interaction_factor: 1.25
    neurite_radius: 0.5
    neurite_interaction_factor: 2.0
    neurite_spring_constant: 5.0
    neurite_default_length: 10.0

  # Cycling and differentitation rates [1/min]
  clocks:
    proliferation_rate: 0.0007
    death_rate: 0.00002
    differentiation_rate: 0.0006

  # Number of neurites allowed until differentiation is blocked 
  max_number_of_neurites: 3

# Object interactions
interactions:
  # Interactions may be based on simple adhesion/repulsion functions ["simple"]
  # or potentials functions ["potentials"]
  type: "potentials"
  sphere_sphere_adhesion: 5.0
  sphere_sphere_repulsion: 25.0
  # Smoothness factor should be commented for simple adhesion/repulsion
  sphere_sphere_smoothness: 1
  sphere_cylinder_adhesion: 5.0
  sphere_cylinder_repulsion: 25.0
  # Smoothness factor should be commented for simple adhesion/repulsion
  sphere_cylinder_smoothness: 1
  cylinder_cylinder_adhesion: 5.0
  cylinder_cylinder_repulsion: 15.0
    # Smoothness factor should be commented for simple adhesion/repulsion
  cylinder_cylinder_smoothness: 1